packages/raffles-client/src/components/Auctions/AuctionCard/AuctionCard.stories.tsx
packages/raffles-client/src/components/Auctions/AuctionRanking/AuctionRanking.tsx
packages/raffles-client/src/components/Auctions/AuctionRanking/styles.ts

Refactor ranking to show last spot when no winners. I've added more stories, it's hard to simplify the logic so I think I'll add tests in another PR.

Winners slots

---

packages/raffles-client/src/components/Modals/ConnectWallet/index.tsx
packages/raffles-client/src/components/Modals/ConnectWallet/styles.ts

I create a new branch, the previous one had a conflict of modules

style(wallet-modal): modify modal according to mockup

---

README.md
packages/ps2/src/features/navigation/Header/index.tsx

All buttons and links should have ids. THis is needed for testing purposes and analytics too

chore(ps2): added link ids

---

packages/raffles-client/src/components/Auctions/AuctionCard/AuctionCard.stories.tsx
packages/raffles-client/src/components/Auctions/AuctionRanking/AuctionRanking.tsx

fix(raffle-client): fix mobile rank winner

---

packages/raffles-client/package.json
packages/raffles-client/src/components/Modals/ProjectDetails/index.tsx
packages/raffles-server/src/entities/auctions/model.ts
packages/raffles-server/src/entities/auctions/typeDef.ts
yarn.lock

feat(raffle-client): Add markdown support

---

packages/zignaly-ui/src/components/inputs/Button/styles.ts

fix(ui): fix button box-sizing

---

packages/ps2/src/features/auth/components/AuthVerifyModal/index.tsx

Fix for https://github.com/zignaly-open/zigraffle/issues/161

fix(PS2): use correct API for login verification

---

.github/workflows/release-preprod.yml
.github/workflows/release-test.yml
.github/workflows/release.yml
appspec.yml
build-prod.sh
packages/raffles-server/src/entities/auctions/auction-claim.test.ts
packages/raffles-server/src/entities/auctions/auction.test.ts
packages/raffles-server/src/entities/auctions/constants.ts
packages/raffles-server/src/entities/auctions/repository.ts
scripts/after_install.sh

Master branch will trigger preprod deploy.
Release brach will trigger prod deploy.

chore(raffle-server): get ready for production

---

packages/ps2/public/locales/en/auth.json
packages/ps2/src/features/auth/components/AuthVerifyModal/index.tsx
packages/ps2/src/features/auth/components/AuthVerifyModal/styles.ts
packages/ps2/src/features/auth/components/LoginForm/index.tsx
packages/ps2/src/features/auth/components/TwoFAForm/index.tsx
packages/ps2/src/features/dashboard/components/EditInvestmentModal/forms/EditInvestmentForm/index.tsx
packages/ps2/src/features/dashboard/components/EditInvestmentModal/forms/WithdrawForm/index.tsx
packages/ps2/src/util/hooks/useToast.tsx
packages/zignaly-ui/src/components/inputs/TextButton/index.tsx
packages/zignaly-ui/src/components/inputs/TextButton/types.ts

https://github.com/zignaly-open/zigraffle/issues/150

fix(PS2): login fixes

---

packages/zignaly-ui/src/components/inputs/CheckBox/styles.tsx

fixes https://github.com/zignaly-open/zigraffle/issues/210

Fix(PS2): show selected columns

---

packages/zignaly-ui/src/components/inputs/InputText/styles.ts

https://github.com/zignaly-open/zigraffle/issues/235

fix(PS2): 1password blue highlight

---

packages/ps2/src/features/dashboard/use.tsx

https://github.com/zignaly-open/zigraffle/issues/224

fix(PS2): refetch pending transactions

---

packages/ps2/src/features/dashboard/components/EditInvestmentModal/forms/WithdrawForm/index.tsx

https://github.com/zignaly-open/zigraffle/issues/229

fix(PS2): available for withdrawal

---

packages/ps2/public/locales/en/edit-investment.json
packages/ps2/public/locales/en/withdraw-your-investment.json
packages/ps2/src/features/dashboard/components/EditInvestmentModal/index.tsx
packages/ps2/src/features/dashboard/components/EditInvestmentModal/styles.ts
packages/ps2/src/features/dashboard/components/EditInvestmentModal/views/WithdrawFunds.tsx
packages/zignaly-ui/src/components/inputs/InputAmountAdvanced/styles.tsx

https://github.com/zignaly-open/zigraffle/issues/188

fix(PS2): dashboard edit investment fixes

---

packages/zignaly-ui/src/components/display/Charts/index.tsx
packages/zignaly-ui/src/components/display/Charts/types.ts

https://github.com/zignaly-open/zigraffle/issues/186

fix(PS2): correct graph color

---

packages/raffles-client/src/components/Header/Header.tsx

fix(raffles-client): increase user icon size

---

packages/raffles-client/src/components/Auctions/AuctionCard/AuctionCard.tsx
packages/raffles-client/src/components/Auctions/AuctionCard/styles.ts
packages/raffles-client/src/components/Header/Header.tsx

styling(raffle-client): add style to icon user and chainIcon

---

packages/zignaly-ui/src/components/inputs/InputText/styles.ts

fix(PS2): black box in InputText

---

packages/raffles-client/src/components/Auctions/AuctionCard/AuctionCard.tsx
packages/raffles-client/src/components/Auctions/AuctionCard/styles.ts
packages/raffles-client/src/components/common/ChainIcon.tsx

fix(raffle-client): size and alignment of chain icon

---

packages/raffles-client/src/components/Auctions/AuctionCard/AuctionCard.tsx
packages/raffles-client/src/components/Auctions/AuctionCard/styles.ts

fix(raffle-client): size and alignment chainIcon

---

packages/raffles-client/src/components/Auctions/AuctionCard/AuctionCard.tsx
packages/raffles-client/src/queries/auctions.ts
packages/raffles-server/src/entities/__fixtures/sample-data-long-expiry.json
packages/raffles-server/src/entities/__fixtures/sample-data-short-expiry.json
packages/raffles-server/src/entities/auctions/auction.test.ts
packages/raffles-server/src/entities/auctions/model.ts
packages/raffles-server/src/entities/auctions/repository.ts
packages/raffles-server/src/entities/auctions/typeDef.ts
packages/raffles-server/src/entities/auctions/util.ts
packages/raffles-server/src/util/test-utils.ts

- Store currentBid in the db for easier calculation, incremented by each bid, and avoid the previous concurrency issue not updating the price
- Refetch auction once ended.

refactor(raffle-server): Refactor bids price calculation

---

.github/workflows/deploy-ps2-master.yml

chore(PS2): use prod api

---

packages/ps2/public/locales/en/marketplace.json
packages/ps2/src/views/ProfitSharing/components/Marketplace/index.tsx

chore(PS2): column renaming

---

packages/ps2/src/views/TraderService/components/ServiceProfileContainer/styles.tsx

fix(PS2): fixed height problems

---

packages/ps2/src/views/TraderService/components/ServiceProfileContainer/atoms/ServicePercentageInfo.tsx
packages/zignaly-ui/src/components/display/ZigPriceLabel/index.tsx
packages/zignaly-ui/src/components/display/ZigPriceLabel/stories.tsx
packages/zignaly-ui/src/components/display/ZigPriceLabel/types.tsx
packages/zignaly-ui/src/components/display/ZigPriceLabel/util.ts

fix(PS2): shorten numbers

---

packages/raffles-server/src/entities/balances/service.ts

Initialize balance to 0 in case of null.

Send default balance

---

.github/workflows/deploy-ps2-test.yml

fix(PS2): fixed the automation script

---

packages/ps2/public/locales/en/transactions-history.json
packages/ps2/src/views/Balance/components/TransactionsHistoryTable/atoms/ProviderLink.tsx
packages/ps2/src/views/Balance/components/TransactionsHistoryTable/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5663513147

feat(PS2): handle empty service name

---

packages/ps2/src/views/Dashboard/components/ServiceName/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5807569885

fix(PS2): min width for service name

---

packages/ps2/src/views/Auth/components/AuthVerifyModal/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5612098017

fix(PS2): hide verify input on success

---

packages/ps2/src/views/Auth/components/AuthVerifyModal/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5832456088

fix(PS2): call correct resend endpoint for unverified users

---

packages/ps2/public/locales/en/common.json
packages/ps2/src/views/TraderService/components/EditServiceProfileContainer/validations.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5837424560

feat(PS2): add letter validation

---

packages/ps2/src/apis/user/use.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5584094684

fix(PS2): avoid resetting to english after login

---

packages/ps2/src/views/Dashboard/components/ServiceName/index.tsx
packages/ps2/src/views/ProfitSharing/components/Marketplace/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5807569885

fix(PS2): reduce empty space in service name

---

packages/ps2/src/views/TraderService/components/ApiKeys/modals/EditApiKey.tsx

https://3.basecamp.com/5165237/buckets/24055125/todos/5836313726

feat(PS2): remove api margin trade

---

packages/ps2/src/views/TraderService/components/EditServiceProfileContainer/index.tsx
packages/ps2/src/views/TraderService/components/EditServiceProfileContainer/validations.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5822846893

feat(PS2): add sbt back

---

packages/ps2/src/apis/user/use.tsx
packages/ps2/src/util/walls/AuthenticatedWall.tsx.tsx
packages/ps2/src/views/TraderService/components/ServiceProfileContainer/atoms/InvestButton.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5825460412

feat(PS2): redirect to login if unauthenticated

---

packages/ps2/src/apis/service/use.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5837321538

fix(PS2): fix incorrect padding applied

---

packages/ps2/src/views/Dashboard/components/ManageInvestmentModals/views/InvestorDetailsForService.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5836521765

fix(PS2): edit zero success fee

---

packages/ps2/src/views/TraderService/components/InvestorTable/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5846368167

fix(PS2): edit success fee in table for owner

---

packages/ps2/public/locales/en/service.json
packages/ps2/src/views/TraderService/components/BecomeTraderLanding/modals/forms/CreateServiceForm.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5846358505

fix(PS2): edit text button create service

---

packages/ps2/src/views/TraderService/components/EditServiceProfileContainer/validations.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5857849688

fix(PS2): accept 75% success fee

---

packages/ps2/src/apis/service/use.tsx
packages/ps2/src/apis/store.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5860749206
https://3.basecamp.com/5165237/buckets/24055125/todos/5831388994

fix(PS2): fix session expired infinite loop

---

.github/workflows/deploy-ps2-test.yml
packages/ps2/public/index.html
packages/ps2/src/util/analytics.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5757644434

fix(PS2): fix customerio

---

packages/ps2/public/index.html
packages/raffles-client/public/index.html

https://3.basecamp.com/5165237/buckets/23902424/todos/5858593808

fix(PS2): fix userpilot page event

---

packages/ps2/src/views/Settings/Enable2FAModal/Enable2FaForm.tsx
packages/ps2/src/views/Settings/Enable2FAModal/styles.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5900900842

style(PS2): improve qr code style

---

packages/ps2/src/apis/coin/types.ts
packages/ps2/src/views/Balance/components/TransactionsHistoryTable/atoms/TransactionStateLabel/types.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5906295374

feat(PS2): handle sent status

---

packages/ps2/public/locales/en/transactions-history.json

https://3.basecamp.com/5165237/buckets/24055125/todos/5910395684

fix(PS2): fix filters in transactions

---

packages/ps2/src/views/TraderService/components/ApiKeys/modals/CreateApiKey.tsx
packages/ps2/src/views/TraderService/components/ApiKeys/modals/EditApiKey.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5904849799

feat(PS2): rename button createAPIKey

---

packages/ps2/src/views/Referrals/index.tsx

https://3.basecamp.com/5165237/buckets/31428125/todos/5961465301

fix(PS2): show rewards for no commission guy with invites  CU-861mhqu0b

---

packages/ps2/src/views/TraderService/components/EditServiceProfileContainer/index.tsx
packages/ps2/src/views/TraderService/components/ServiceProfileContainer/styles.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5956806701

fix(PS2): fix description input

---

packages/ps2/src/util/i18next.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5966165547

feat(PS2): more languages

---

packages/zignaly-ui/src/components/display/ZigChart/styles.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5991640133

fix(PS2): fix tooltip hidden my toolbar

---

packages/zignaly-ui/src/components/inputs/InputCode/styles.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5991373372

fix(PS2): cells alignment in verify email

---

packages/ps2/src/util/constants.ts
packages/ps2/src/views/Dashboard/components/ManageInvestmentModals/forms/DepositForm/index.tsx
packages/ps2/src/views/Dashboard/components/ManageInvestmentModals/views/ChooseDepositType.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5996105434

chore(PS2): replace buy crypto link

---

packages/ps2/src/views/Wallet/modals/BuyZigModal/AddUsdtForm.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5934095338

feat(PS2): new buy zig modal view

---

packages/ps2/src/components/Navigation/Header/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6002280138

fix(PS2): fix login alignment

---

packages/ps2/src/components/Navigation/Drawer/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6000811355

feat(PS2): wallet menu

---

packages/ps2/src/util/hooks/useInfinitePaginatedQuery.ts

https://3.basecamp.com/5165237/buckets/24055125/todos/5970993805

fix(PS2): pagination in balances table

---

packages/ps2/public/locales/en/my-dashboard.json
packages/ps2/src/views/Dashboard/components/InvestingSteps/InvestingLayout.tsx
packages/ps2/src/views/Dashboard/components/InvestingSteps/InvestingStep.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5966537790

feat(PS2): edit button aligment in steps

---

packages/ps2/src/components/Navigation/Drawer/index.tsx

Reverts zignaly-open/zignaly-neo#639

Revert "feat(PS2): add ps menu in mobile"

---

packages/ps2/src/views/TraderService/components/ServiceHeader/atoms.tsx
packages/ps2/src/views/TraderService/components/ServiceHeader/index.tsx
packages/zignaly-ui/src/components/navigation/MenuDropDown/index.tsx
packages/zignaly-ui/src/components/navigation/MenuDropDown/types.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5951148297

feat(PS2): add ids to service profile header

---

packages/ps2/public/locales/en/referrals.json

https://3.basecamp.com/5165237/buckets/31428125/todos/6002296592

feat(PS2): edit text no earnings history

---

packages/ps2/src/components/Navigation/Drawer/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6013093694

feat(PS2): add back ps menu for mobile

---

packages/ps2/src/util/constants.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/5996105434

fix(PS2): replace buy crypto link

---

packages/ps2/public/locales/en/my-dashboard.json

https://3.basecamp.com/5165237/buckets/23902424/todos/6012860868

fix(PS2): edit text steps portfolio

---

packages/ps2/src/views/Auth/components/EmailVerifyForm/styles.ts
packages/ps2/src/views/Auth/components/TwoFAForm/styles.ts
packages/zignaly-ui/src/components/inputs/InputCode/styles.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/6007194686

fix(PS2): left alignment of error

---

packages/ps2/src/views/Dashboard/components/ManageInvestmentModals/forms/WithdrawInvestmentForm/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6022134988

fix(PS2): remove scientific notation in withdraw modal

---

packages/ps2/public/locales/en/wallet.json
packages/ps2/src/views/Wallet/modals/BuyZigModal/AddUsdtForm.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6016901809

chore(PS2): edit buy zig modal text

---

packages/ps2/src/views/Auth/components/AuthVerifyModal/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6033850290

fix(PS2): delete verification code if it's wrong

---

packages/ps2/public/locales/en/offer-your-trading-service.json
packages/ps2/src/views/TraderService/components/BecomeTraderLanding/index.tsx
packages/ps2/src/views/TraderService/components/BecomeTraderLanding/styles.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/6012603562

fix(PS2): text alignment become trader page

---

packages/ps2/src/views/TraderService/components/BecomeTraderLanding/index.tsx
packages/ps2/src/views/TraderService/components/ServiceProfileContainer/atoms/ServiceInformation.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6027889944

fix(PS2) add ctaIds

---

packages/ps2/src/views/Auth/components/AuthVerifyModal/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6038676604

fix(PS2): alignment 2fa if verifyStatus succeded

---

packages/ps2/src/views/Dashboard/components/ServiceName/index.tsx
packages/ps2/src/views/ProfitSharing/components/Marketplace/index.tsx
packages/zignaly-ui/src/components/display/Table/components/PercentageIndicator/index.tsx
packages/zignaly-ui/src/components/display/ZigTable/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6043387765

feat(PS2): add more ids marketplace

---

packages/ps2/src/views/TraderService/components/InvestorTable/index.tsx

https://3.basecamp.com/5165237/buckets/24055125/todos/5970967765

fix(PS2): sorting bug investors view

---

packages/ps2/src/views/Dashboard/components/ManageInvestmentModals/forms/WithdrawInvestmentForm/index.tsx
packages/zignaly-ui/src/index.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/6022134988

fix(PS2): remove scientific notation withdraw

---

packages/ps2/src/views/Dashboard/components/MyDashboard/styles.ts
packages/ps2/src/views/TraderService/components/styles.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/6063453873

fix(PS2): add paddings portfolio and manage service

---

packages/ps2/src/views/Dashboard/components/MyDashboard/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6055564786

fix(PS2): default sorting my portfolio table

---

packages/zignaly-ui/src/components/display/ZigTable/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6048034916

fix(PS2): remove filter all columns my coins

---

packages/ps2/src/components/Navigation/Header/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6069265832

fix(PS2): update id zignaly logo header

---

packages/ps2/public/locales/en/management.json
packages/ps2/public/locales/es/management.json
packages/ps2/public/locales/pt/management.json
packages/ps2/public/locales/ru/management.json
packages/ps2/public/locales/tr/management.json
packages/ps2/public/locales/vi/management.json
packages/ps2/src/views/TraderService/components/ApiKeys/ApiKeyManagement.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6087995120

feat(PS2): remove trading.zignaly.com

---

packages/ps2/src/apis/investment/use.tsx
packages/ps2/src/apis/user/api.ts
packages/ps2/src/components/Navigation/BalanceButton/index.tsx

https://3.basecamp.com/5165237/buckets/24055125/todos/6005300581

feat(PS2): refresh balance after investment

---

packages/ps2/src/components/CoinLabel/index.tsx
packages/ps2/src/components/CoinLabel/types.tsx
packages/ps2/src/views/Balance/components/BalanceAccountSelector/index.tsx
packages/ps2/src/views/Balance/components/MyBalancesTable/index.tsx
packages/zignaly-ui/src/components/display/ZigCoinIcon/index.tsx
packages/zignaly-ui/src/components/display/ZigCoinIcon/types.ts
packages/zignaly-ui/src/components/display/ZigDropdown/index.tsx
packages/zignaly-ui/src/components/display/ZigDropdown/types.ts
packages/zignaly-ui/src/components/display/ZigTable/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5951127066

feat(PS2): add ids my balances coins

---

packages/ps2/public/locales/en/edit-investment.json
packages/ps2/public/locales/en/withdraw-your-investment.json
packages/ps2/src/views/Dashboard/components/ManageInvestmentModals/styles.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/6112731197

chore(PS2): update texts in withdraw modals

---

packages/tracker/src/index.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/6079154013

feat(tracker): update tz url

---

packages/ps2/src/views/TraderService/components/ServiceProfileContainer/atoms/PercentChange.tsx
packages/ps2/src/views/TraderService/components/ServiceProfileContainer/atoms/ServiceGrowthChart.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6089288262

feat(PS2): add shorten to PercentChange

---

packages/ps2/src/App.tsx
packages/ps2/src/apis/baseQuery.ts
packages/ps2/src/apis/store.ts
packages/ps2/src/apis/user/use.tsx
packages/ps2/src/apis/user/util.ts

We had a problem with Header not being a part of Suspense. Tricky one.

fix(PS2): logout cache issues

---

packages/ps2/src/util/constants.ts
packages/ps2/src/views/Auth/Signup.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6101929751

feat(PS2): add links and fix paddings signup page

---

packages/ps2/src/views/Wallet/components/WalletTopPanel/index.tsx
packages/ps2/src/views/Wallet/components/WalletTopPanel/styles.ts
packages/ps2/src/views/Wallet/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6108201426

fix(PS2): improve wallet padding

---

packages/ps2/src/views/Wallet/components/WalletTopPanel/styles.ts

https://3.basecamp.com/5165237/buckets/23902424/todos/6108201426

fix(PS2): fix subtitle padding

---

packages/ps2/src/views/Balance/components/TransactionsHistoryTable/atoms/FromTo/index.tsx
packages/ps2/src/views/Balance/components/TransactionsHistoryTable/atoms/ProviderLink.tsx
packages/ps2/src/views/Balance/components/TransactionsHistoryTable/atoms/TransactionDetails/index.tsx
packages/ps2/src/views/Balance/components/TransactionsHistoryTable/atoms/TransactionStateLabel/index.tsx
packages/ps2/src/views/Balance/components/TransactionsHistoryTable/atoms/TransferZigLabel.tsx
packages/ps2/src/views/Balance/components/TransactionsHistoryTable/index.tsx
packages/ps2/src/views/Balance/index.tsx
packages/zignaly-ui/src/components/display/ZigTable/components/DateLabel/index.tsx
packages/zignaly-ui/src/components/display/ZigTable/index.tsx
packages/zignaly-ui/src/components/inputs/ZigSelect/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/5951127480

feat(PS2): add ids to transactions

---

packages/ps2/src/views/Dashboard/components/MyDashboard/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6116272564

fix(PS20: min height portfolio table row

---

packages/ps2/src/views/Auth/components/ForgotPasswordForm/index.tsx
packages/ps2/src/views/Auth/components/ResetPasswordForm/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6117652806

feat(PS2): forgot password ids and style

---

packages/ps2/src/views/Wallet/components/WalletTopPanel/styles.ts
packages/ps2/src/views/Wallet/index.tsx

Not enough margin on medium screens

fix: restore wallet margin

---

packages/ps2/src/views/TraderService/components/ServiceProfileContainer/index.tsx

https://3.basecamp.com/5165237/buckets/23902424/todos/6048000799

fix(PS2): responsive profile

---

.github/workflows/ci.yml
.github/workflows/deploy-ps2-prod.yml
.github/workflows/deploy-ps2-staging.yml
.github/workflows/deploy-ps2-test.yml

https://lerna.js.org/docs/legacy-package-management

fix(PS2): keep using lerna 6

---

packages/ps2/src/apis/user/api.ts
packages/ps2/src/apis/user/types.ts
packages/ps2/src/components/Navigation/HeaderWidgetButtons/BalanceButton/index.tsx

This reverts commit 73a185b426f99ebde5148951142b9a5c9fe4167c.

Revert "fix: fix balance number"

---

packages/ps2/src/apis/user/api.ts
packages/ps2/src/apis/user/types.ts
packages/ps2/src/components/Navigation/HeaderWidgetButtons/BalanceButton/index.tsx

This reverts commit e00813ddcfaea7f179226e5f3f723361c7cb980c.

fix: fix balance number

---

packages/ps2/public/locales/en/deposit-crypto.json
packages/ps2/public/locales/en/edit-investment.json
packages/ps2/public/locales/en/error.json
packages/ps2/public/locales/en/investors.json
packages/ps2/public/locales/en/management.json
packages/ps2/public/locales/en/offer-your-trading-service.json
packages/ps2/public/locales/en/referrals-trader.json
packages/ps2/public/locales/en/referrals.json
packages/ps2/public/locales/en/rewards.json
packages/ps2/public/locales/en/service.json
packages/ps2/public/locales/en/settings.json
packages/ps2/public/locales/en/sign-up.json
packages/ps2/public/locales/en/wallet.json
packages/ps2/src/util/i18n/i18next.ts

Reverts zignaly-open/zignaly-neo#1356

Revert "feat(PS2): custom wl name"

---

packages/zignaly-ui/src/components/filters/ZigFilters/dropdowns/atoms/FilterCount/index.tsx

Avenir Next font vertical alignment hack + horizonal fix.

fix(UI): adjust font padding

---

packages/ps2/public/locales/en/legal.json
packages/ps2/public/locales/en/pages.json
packages/ps2/src/Router.tsx
packages/ps2/src/routes.ts
packages/ps2/src/views/Auth/components/SignupForm/index.tsx
packages/ps2/src/views/Legal/Privacy.tsx
packages/ps2/src/views/Legal/TermsOfService.tsx
packages/ps2/src/views/Legal/components.ts
packages/ps2/src/views/Referrals/styles.ts
yarn.lock

feat(Legal): ugly legal pages

---

packages/ps2/src/views/ProfitSharing/components/Marketplace/index.tsx
packages/ps2/src/views/ProfitSharing/components/ServiceCard/index.tsx

This reverts commit 1f4e90136a59f933becbc95407743a7507a8c5a2.

fix(PS2): revert pnl placeholder

---

packages/backoffice/src/util/i18next.ts
packages/ps2/src/util/i18n/i18next.ts
packages/ps2/src/whitelabel/clients/zignaly.ts

fix(i18nDetector): proper language detection
